"""PS13/PS14 control framework mappings (illustrative edition; licensed text validation is a
customer onboarding step). States: supports-evidence | partial | unmapped. Unmapped is
disclosed, never fabricated (G30). ATT&CK references only supported behaviors (PS14)."""
CONTROL_MAP: dict[str, dict] = {
    "CLD-002": {"status": "supports-evidence", "controls": ["SOC2-CC6.1 (example edition)"],
                "attack": None},
    "CLD-007": {"status": "supports-evidence", "controls": ["SOC2-CC6.1 (example edition)"],
                "attack": None},
    "CLD-008": {"status": "supports-evidence", "controls": ["SOC2-CC6.1 (example edition)"],
                "attack": "T1078.004 - Valid Accounts: Cloud Accounts (behavior-specific; review)"},
    "CLD-009": {"status": "supports-evidence", "controls": ["SOC2-CC6.2 (example edition)"],
                "attack": None},
    "KEY-001": {"status": "partial", "controls": ["SOC2-CC6.1, CC7.1 (example edition)"],
                "note": "Pattern candidate only; validity untested by design (G23).",
                "attack": "T1552.004 - Unsecured Credentials: Private Keys (candidate context)"},
    "KEY-003": {"status": "supports-evidence", "controls": ["SOC2-CC6.1 (example edition)"],
                "attack": None},
    "KEY-007": {"status": "partial", "controls": ["SOC2-CC6.1 (example edition)"],
                "note": "Duplicate credentials correlate via tenant fingerprints only."},
    "OAU-001": {"status": "supports-evidence", "controls": ["SOC2-CC6.1 (example edition)"],
                "attack": None},
    "OAU-004": {"status": "partial", "controls": ["SOC2-CC6.1 (example edition)"],
                "note": "Third-party app review process evidence lives outside passive scope."},
    "CICD-006": {"status": "supports-evidence", "controls": ["SOC2-CC6.1, CC8.1 (example edition)"],
                 "attack": "T1550.001 - Use Alternate Authentication Material (review required)"},
    "CICD-007": {"status": "supports-evidence", "controls": ["SOC2-CC8.1 (example edition)"],
                 "attack": "T1195.002 - Supply Chain Compromise: Compromise Software Supply Chain"},
    "AGI-002": {"status": "supports-evidence", "controls": ["SOC2-CC6.1 (example edition)"],
                "attack": None},
    "AGI-004": {"status": "supports-evidence", "controls": ["SOC2-CC6.2 (example edition)"],
                "attack": None},
    "AGI-005": {"status": "supports-evidence", "controls": ["SOC2-CC6.6 (example edition)"],
                "attack": "T1195.002 - Supply Chain Compromise (tool poisoning prerequisite)"},
    "AGI-006": {"status": "supports-evidence", "controls": ["SOC2-CC6.1 (example edition)"],
                "attack": None},
    "AGI-008": {"status": "supports-evidence", "controls": ["SOC2-CC6.2 (example edition)"],
                "attack": None},
    "AGI-011": {"status": "supports-evidence", "controls": ["SOC2-CC6.6 (example edition)"],
                "attack": None},
    "AGI-014": {"status": "supports-evidence", "controls": ["SOC2-CC6.6 (example edition)"],
                "attack": "T1041 - Exfiltration Over CNG (egress policy context; review)"},
    "AGI-015": {"status": "supports-evidence", "controls": ["SOC2-CC6.1, CC7.3 (example edition)"],
                "attack": None},
    "INV-001": {"status": "supports-evidence", "controls": ["SOC2-CC7.1 (example edition)"],
                "attack": None},
    "INV-002": {"status": "supports-evidence", "controls": ["SOC2-CC7.1 (example edition)"],
                "attack": None},
}
