#!/usr/bin/env python
"""Generate docs/TRACEABILITY.md: blueprint requirement IDs -> where they live in code/tests.

BG01/BG15 requirement: a requirement index with IDs, source tab and planned test before
implementation, plus per-iteration reporting of implemented IDs. This script regenerates
the matrix from docs/blueprint/requirements.json by scanning the tree for ID references.

Usage: python scripts/gen_traceability.py
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQ = ROOT / "docs" / "blueprint" / "requirements.json"
OUT = ROOT / "docs" / "TRACEABILITY.md"

SCAN_DIRS = ["nhi_sentinel", "tests", "web", "docs", "fixtures"]
SKIP_SUFFIXES = {".xlsx", ".db", ".png", ".pyc"}
ID_RE = re.compile(r"\b((?:CLD|KEY|OAU|CRT|CICD|K8S|RPA|ADS|AGI|SSH|DET|INV)-\d{3}|"
                   r"(?:G|D|AR|SC|EX|CN|PS|UI|UX|VD|API|OP|OF|B|AT|K|R|BG|S)\d{2})\b")


def load_ids() -> dict[str, dict]:
    data = json.loads(REQ.read_text(encoding="utf-8"))
    ids: dict[str, dict] = {}
    for sheet, spec in data["sheets"].items():
        for item in spec["items"]:
            rid = item["id"]
            ids.setdefault(rid, {"sheet": sheet, "title": next(iter(
                (v for k, v in item.items() if k.lower() in
                 ("check", "decision", "component", "control", "id / object", "contract",
                  "node", "source", "check id", "subject", "screen", "pattern", "area",
                  "method", "work package", "test area", "metric", "risk", "step",
                  "reference", "original sheet / id"))), ""), "files": set(), "tests": set()})
    return ids


def scan(ids: dict[str, dict]) -> None:
    for d in SCAN_DIRS:
        base = ROOT / d
        if not base.exists():
            continue
        for p in base.rglob("*"):
            if not p.is_file() or p.suffix.lower() in SKIP_SUFFIXES:
                continue
            if p.resolve() in (REQ.resolve(), OUT.resolve()):
                continue  # the index and its own output match every ID - not evidence
            try:
                text = p.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            rel = p.relative_to(ROOT).as_posix()
            is_test = rel.startswith("tests/")
            for m in ID_RE.finditer(text):
                if m.group(0) in ids:
                    (ids[m.group(0)]["tests"] if is_test else ids[m.group(0)]["files"]).add(rel)


def main() -> int:
    ids = load_ids()
    scan(ids)
    implemented = sum(1 for v in ids.values() if v["files"] or v["tests"])
    by_sheet: dict[str, list[str]] = defaultdict(list)
    for rid, v in ids.items():
        by_sheet[v["sheet"]].append(rid)

    lines = ["# Traceability matrix (generated)",
             "",
             f"Source: `docs/blueprint/requirements.json` (blueprint v2 extraction). "
             f"{implemented}/{len(ids)} requirement IDs are referenced by code or tests.",
             "",
             "An ID listed here means the codebase or tests *reference* it; implementation",
             "depth is documented in the ADRs and README. Generated by `scripts/gen_traceability.py`.",
             ""]
    for sheet in sorted(by_sheet):
        rids = sorted(by_sheet[sheet])
        covered = [r for r in rids if ids[r]["files"] or ids[r]["tests"]]
        lines.append(f"## {sheet} — {len(covered)}/{len(rids)} referenced")
        lines.append("")
        lines.append("| ID | Title | Code/doc refs | Tests |")
        lines.append("|---|---|---|---|")
        for rid in rids:
            v = ids[rid]
            files = ", ".join(f"`{f}`" for f in sorted(v["files"])[:4])
            tests = ", ".join(f"`{t}`" for t in sorted(v["tests"])[:3])
            title = (v["title"] or "")[:70].replace("|", "/")
            lines.append(f"| {rid} | {title} | {files} | {tests} |")
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.name}: {implemented}/{len(ids)} IDs referenced")
    return 0


if __name__ == "__main__":
    sys.exit(main())
